chore: renamed boilerplate leftovers and edited the openapi
MapColonies/metatile-queue-populator pull request #1
Opened 2022-02-15 13:30 UTC by CptSchnitz

2022-02-15 21:29 UTC, vitaligi requested changes

2022-02-15 21:29 UTC, vitaligi commented on openapi3.yaml
> +    tilesRequest:
`TilesRequest` use pascal case

2022-02-15 21:29 UTC, vitaligi commented on openapi3.yaml
> +        bbox:
add an example for `bbox`, currently the example shows an invalid `bbox` [0,0,0,0]

2022-02-15 21:29 UTC, vitaligi commented on openapi3.yaml
> +          maximum: 18
should we limit it to 18 or some larger value, the same for `minZoom`
perhaps add a description indicating `maxZoom` must be equal to at least `minZoom`

2022-02-16 06:27 UTC, CptSchnitz commented on openapi3.yaml
> +          maximum: 18
in regards to the max value of the zoom, i think later we can make it configurable.

2022-02-16 06:32 UTC, CptSchnitz commented on openapi3.yaml
> +    tilesRequest:
fixed

2022-02-16 06:32 UTC, CptSchnitz commented on openapi3.yaml
> +        bbox:
added

2022-02-16 06:32 UTC, CptSchnitz commented on openapi3.yaml
> +          maximum: 18
Added better description

2022-02-16 11:01 UTC, vitaligi approved these changes

2022-02-16 11:28 UTC, merged