feat!: multi areal request and geojson support
MapColonies/metatile-queue-populator pull request #12
Opened 2023-06-27 13:19 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2023-06-28 06:33 UTC, syncush requested changes

2023-06-28 06:33 UTC, syncush commented on openapi3.yaml
> +  /tiles/area:
I couldn't comment on the right line, but please bump the version of the API to v2.0.0

2023-06-28 06:33 UTC, syncush commented on openapi3.yaml
> +    Geometry:
I thought of having minZoom and maxZoom per feature while we can set a global minZoom and maxZoom if we didn't set

2023-06-28 06:33 UTC, syncush commented on src/tiles/models/tilesManager.ts
> +    const key = hashValue(payload);
hey maybe I missed it, but I was reading the code multiple times and couldn't remember why we hash the payload.
Can you please remind me?

2023-07-02 09:24 UTC, melancholiai commented on openapi3.yaml
> +  /tiles/area:
`standard-version` will take care of this once we release

2023-07-02 09:25 UTC, melancholiai commented on openapi3.yaml
> +    Geometry:
thought about it too, but it was suggested that this might be prone to human error

2023-07-02 09:25 UTC, melancholiai commented on src/tiles/models/tilesManager.ts
> +    const key = hashValue(payload);
this payload is to be pushed to the `request_queue`, in the case where a request of the exact same parameters is already present in the queue there is no need to add it once again to the queue to be fetched in future for rendering. hence the hashing and the functionality of `pgboss.sendOnce` having unique key

2023-07-02 11:26 UTC, syncush commented on openapi3.yaml
> +    Geometry:
what about setting a global?

2023-07-02 11:29 UTC, syncush commented on src/tiles/models/tilesManager.ts
> +    const key = hashValue(payload);
got it

2023-07-03 19:55 UTC, syncush approved these changes

2023-07-11 08:18 UTC, melancholiai commented on openapi3.yaml
> +    Geometry:
sounds like another level of complexity for not much, if a necessity comes I'm in favour to revisit this

2023-07-11 11:28 UTC, merged