feat: added option to customize job parameters
MapColonies/metatile-queue-populator pull request #8
Opened 2022-04-07 13:05 UTC by CptSchnitz

2022-04-07 13:39 UTC, melancholiai requested changes

2022-04-07 13:39 UTC, melancholiai commented on README.md
> +- DB_JOBS_RETRY_DELAY - Default: 60. Delay between retries of failed jobs, in seconds.
I know `pgboss` called this option `retryDelay` but let's be consistent with adding the time unit

2022-04-07 13:39 UTC, melancholiai commented on config/custom-environment-variables.json
> +    }
nest under jobs

2022-04-07 13:41 UTC, CptSchnitz commented on config/custom-environment-variables.json
> +    }
no, it's more work

2022-04-07 13:42 UTC, melancholiai commented on README.md
> +- DB_JOBS_RETRY_DELAY - Default: 60. Delay between retries of failed jobs, in seconds.
specify the default value of each variable

2022-04-11 10:16 UTC, melancholiai approved these changes

2022-04-12 04:31 UTC, merged